### ISSUE TITLE
IC2 Classic Support?

### ISSUE THREAD

**Issue by sameer** [gamerforEA/IC2-FakePlayers#2]
Hi,
I would love to use this on my server, but I am using IC2 Classic version 1.1.3.7. Is it possible for this mod to be made compatible with IC2 Classic?

Thanks!

**Comment by sameer** [comment]
@gamerforEA ?

**Comment by gamerforEA** [comment]
Hi,
Sorry for being late. IC2 Classic fixed but not will be published.
slowpoke.jpg
